### PR TITLE
temp linux panic fix

### LINKED ISSUE #134: Panic/segmentation fault on GNU/Linux
**Describe the bug**
Running most commands on linux return an error.

**Environment information:**

- OS: GNU/Linux
- Platform: Linux 4.19.0-1-amd64 x86_64
- Firmware Version: Not relevant
- Go
```
GOARCH="amd64"
GOBIN=""
GOCACHE=".cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/gocode"
GOPROXY=""
GORACE=""
GOROOT="/opt/go"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build083768146=/tmp/go-build -gno-record-gcc-switches"
```

**Steps to Reproduce**

1. Go to source code root dir
2. go run cmd/cli/cli.go wipe

**Actual behavior**
```
go run cmd/cli/cli.go wipe
[2019-05-29T21:37:42-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-05-29T21:37:42-04:00] ERROR [walletusb]: current configuration 1
[2019-05-29T21:37:42-04:00] INFO [skywallet]: Wipe device 26! Answer is: 0806

[2019-05-29T21:37:42-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:42-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-05-29T21:37:42-04:00] ERROR [walletusb]: current configuration 1
[2019-05-29T21:37:44-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:44-04:00] INFO [walletusb]: finishing read queue
[2019-05-29T21:37:44-04:00] WARN [walletusb]: Warning: error at releasing interface: LIBUSB_ERROR_NOT_FOUND
[2019-05-29T21:37:44-04:00] WARN [walletusb]: Warning: error at re-attaching driver: LIBUSB_ERROR_OTHER
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6ed881]

runtime stack:
runtime.throw(0x7999fe, 0x2a)
        /opt/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall]:
runtime.cgocall(0x6efb80, 0xc0001137d0, 0x39)
        /opt/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0001137a0 sp=0xc000113768 pc=0x40868b
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb._Cfunc_libusb_close(0x12d6760)
        _cgo_gotypes.go:618 +0x41 fp=0xc0001137d0 sp=0xc0001137a0 pc=0x679e91
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close.func1(0x12d6760)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x56 fp=0xc000113808 sp=0xc0001137d0 pc=0x680226
github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close(0x12d6760)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x2b fp=0xc000113820 sp=0xc000113808 pc=0x67f20b
github.com/skycoin/hardware-wallet-go/src/skywallet/usb.(*LibUSBDevice).Close(0xc00009ce20, 0xc000113800, 0xc0001138b0, 0xc0001138e0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/skywallet/usb/libusb.go:404 +0x109 fp=0xc000113878 sp=0xc000113820 pc=0x683879
github.com/skycoin/hardware-wallet-go/src/skywallet.(*Device).Wipe(0xc000095b90, 0x2, 0xc0001801c0, 0xe, 0x40, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet.go:784 +0x2a6 fp=0xc000113928 sp=0xc000113878 pc=0x6d24c6
github.com/skycoin/hardware-wallet-go/src/cli.wipeCmd.func1(0xc0000c2580)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/cli/wipe.go:42 +0xf6 fp=0xc0001139a8 sp=0xc000113928 pc=0x6e3316
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.HandleAction(0x71d860, 0x7a0a80, 0xc0000c2580, 0xc0000ac400, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/app.go:492 +0x7c fp=0xc0001139d0 sp=0xc0001139a8 pc=0x60478c
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.Command.Run(0x78d02e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x79ea9b, 0x3f, 0x0, ...)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/command.go:210 +0x996 fp=0xc000113c30 sp=0xc0001139d0 pc=0x605986
github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli.(*App).Run(0xc0000d0b60, 0xc00009c020, 0x2, 0x2, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/vendor/github.com/urfave/cli/app.go:255 +0x6af fp=0xc000113f20 sp=0xc000113c30 pc=0x602b0f
github.com/skycoin/hardware-wallet-go/src/cli.(*App).Run(...)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/src/cli/cli.go:124
main.main()
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-go/cmd/cli/cli.go:17 +0xd1 fp=0xc000113f98 sp=0xc000113f20 pc=0x6e3ee1
runtime.main()
        /opt/go/src/runtime/proc.go:200 +0x20c fp=0xc000113fe0 sp=0xc000113f98 pc=0x432a1c
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000113fe8 sp=0xc000113fe0 pc=0x45c831
exit status 2
```

**Expected behavior**
No error at all

**Additional context**
PD: some command work and other not, but the error log is always present

**Possible implementation**
no hint

### PR DESCRIPTION
**Pull request by therealssj**
Fixes #134 

Changes:
- Fix linux panic on device close

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuff specs?
no

Requires testing
yes

tested manually

### CODE REVIEW

**Comment by stdevAlDen** [comment]
@therealssj looks like working, I'm going to test more, this is the output for a wipe:
```bash
[2019-06-03T14:48:40-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-06-03T14:48:40-04:00] ERROR [walletusb]: current configuration 1
[2019-06-03T14:48:40-04:00] INFO [walletusb]: finishing read queue
[2019-06-03T14:48:40-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-06-03T14:48:40-04:00] ERROR [walletusb]: current configuration 1
[2019-06-03T14:48:42-04:00] INFO [walletusb]: finishing read queue
[2019-06-03T14:48:43-04:00] ERROR [skycoin-hw-cli]: proto: wrong wireType = 2 for field MsgType
```

As source of the bug I found:
- https://github.com/skycoin/hardware-wallet-go/commit/b5fd3c31791ebe8550007a5208dfd402351f397f
- https://github.com/skycoin/hardware-wallet-go/commit/868ed41bc873c307fbfd4b9264244f7767b3c071

Currently the lib have not any release, and the community have only 3 active developer consider opening an issue for changing the base lib in a future release if is possible to find a better alternative as a research result.

**Comment by stdevAlDen** [comment]
@therealssj integration tests for daemon [still not working](https://github.com/skycoin/hardware-wallet-daemon/issues/69) after taking this change into the daemon vendors.

PD: I'm not sure that this is the root cause.

Log:
------

```bash
make test-integration-wallet
./ci-scripts/integration-test.sh -m USB -n wallet-integration
++ mktemp -d -t daemon-data-dir.XXXXXX
+ DATA_DIR=/tmp/daemon-data-dir.dwdY09
+ echo 'compiling daemon with coverage'
compiling daemon with coverage
+ go test -c -ldflags '-X github.com/skycoin/hardware-wallet-daemon/cmd/daemon.Commit=7a75deb0861f408b4c2998473fdb973b414f354c -X github.com/skycoin/hardware-wallet-daemon/cmd/daemon.Branch=master' -tags testrunmain -o daemon-integration-wallet-integration.test -coverpkg=github.com/skycoin/hardware-wallet-daemon/... ./cmd/daemon/
+ mkdir -p coverage/
+ echo 'starting daemon node in background with http listener on http://127.0.0.1:9510'
starting daemon node in background with http listener on http://127.0.0.1:9510
+ DAEMON_PID=20193
+ echo 'daemon pid=20193'
daemon pid=20193
+ set +e
+ AUTO_PRESS_BUTTONS=
+ HW_DAEMON_INTEGRATION_TESTS=1
+ HW_DAEMON_INTEGRATION_TEST_MODE=USB
+ ./daemon-integration-wallet-integration.test -web-interface-port=9510 -data-dir=/tmp/daemon-data-dir.dwdY09 -test.run '^TestRunMain$' -test.coverprofile=coverage/daemon-integration-wallet-integration.test.coverage.out -daemon-mode USB
+ USE_CSRF=
+ go test ./src/api/integration/... -timeout=60m
[2019-06-03T15:47:25-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-06-03T15:47:25-04:00] ERROR [walletusb]: current configuration 1
[2019-06-03T15:47:25-04:00] INFO [walletusb]: finishing read queue
[2019-06-03T15:47:25-04:00] INFO [walletusb]: bLength 18
bDescriptorType 1
bcdUSB 2.00
bDeviceClass 0
bDeviceSubClass 0
bDeviceProtocol 0
bMaxPacketSize0 64
idVendor 0x313a
idProduct 0x0001
bcdDevice 1.00
iManufacturer 1
iProduct 2
iSerialNumber 3
bNumConfigurations 1
[2019-06-03T15:47:25-04:00] ERROR [walletusb]: current configuration 1
[2019-06-03T15:47:28-04:00] INFO [walletusb]: finishing read queue
[2019-06-03T15:47:28-04:00] INFO [daemon-api]: 200 DELETE /api/v1/wipe 2.679006798s
[2019-06-03T15:47:28-04:00] INFO [walletusb]: finishing read queue
[2019-06-03T15:47:28-04:00] WARN [walletusb]: Warning: error at releasing interface: LIBUSB_ERROR_NOT_FOUND
[2019-06-03T15:47:28-04:00] WARN [walletusb]: Warning: error at re-attaching driver: LIBUSB_ERROR_OTHER
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x888dd1]

runtime stack:
runtime.throw(0x998439, 0x2a)
        /opt/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 35 [syscall]:
runtime.cgocall(0x88b0d0, 0xc000127658, 0x39)
        /opt/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000127628 sp=0xc0001275f0 pc=0x40892b
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb._Cfunc_libusb_close(0x7f7750001010)
        _cgo_gotypes.go:618 +0x41 fp=0xc000127658 sp=0xc000127628 pc=0x697011
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close.func1(0x7f7750001010)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x56 fp=0xc000127690 sp=0xc000127658 pc=0x69d3a6
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb.Close(0x7f7750001010)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/usb/lowlevel/libusb/libusb.go:1035 +0x2b fp=0xc0001276a8 sp=0xc000127690 pc=0x69c38b
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/usb.(*LibUSBDevice).Close(0xc0002562e0, 0x9a9400, 0xc000294040, 0x5)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/usb/libusb.go:404 +0x109 fp=0xc000127700 sp=0xc0001276a8 pc=0x6a09f9
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet.(*Device).Connect(0xc000176420, 0xc000178000, 0x800)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet.go:138 +0xbd fp=0xc000127740 sp=0xc000127700 pc=0x6f3c4d
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet.(*Device).SetMnemonic(0xc000176420, 0xc000294000, 0x45, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/hardware-wallet-go/src/skywallet/skywallet.go:748 +0x58 fp=0xc0001277b8 sp=0xc000127740 pc=0x6f7968
github.com/skycoin/hardware-wallet-daemon/src/api.setMnemonic.func1(0xa35780, 0xc0001ea200, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/api/set_mnemonic.go:58 +0x564 fp=0xc0001278b0 sp=0xc0001277b8 pc=0x876dd4
net/http.HandlerFunc.ServeHTTP(0xc0000bf160, 0xa35780, 0xc0001ea200, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc0001278d8 sp=0xc0001278b0 pc=0x820f64
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/http.ElapsedHandler.func1(0xa35c00, 0xc000290000, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/http/log.go:17 +0xfc fp=0xc0001279c8 sp=0xc0001278d8 pc=0x85f9ac
net/http.HandlerFunc.ServeHTTP(0xc000176fc0, 0xa35c00, 0xc000290000, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc0001279f0 sp=0xc0001279c8 pc=0x820f64
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/rs/cors.(*Cors).Handler.func1(0xa35c00, 0xc000290000, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/rs/cors/cors.go:207 +0x1af fp=0xc000127a48 sp=0xc0001279f0 pc=0x86683f
net/http.HandlerFunc.ServeHTTP(0xc0000bf180, 0xa35c00, 0xc000290000, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc000127a70 sp=0xc000127a48 pc=0x820f64
github.com/skycoin/hardware-wallet-daemon/src/api.originRefererCheck.func2(0xa35c00, 0xc000290000, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/api/middleware.go:138 +0x140 fp=0xc000127b18 sp=0xc000127a70 pc=0x8758e0
net/http.HandlerFunc.ServeHTTP(0xc0000bf1a0, 0xa35c00, 0xc000290000, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc000127b40 sp=0xc000127b18 pc=0x820f64
github.com/skycoin/hardware-wallet-daemon/src/api.hostCheck.func2(0xa35c00, 0xc000290000, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/api/middleware.go:70 +0x2a7 fp=0xc000127bb8 sp=0xc000127b40 pc=0x8755e7
net/http.HandlerFunc.ServeHTTP(0xc0000b5240, 0xa35c00, 0xc000290000, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc000127be0 sp=0xc000127bb8 pc=0x820f64
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0xa35ac0, 0xc00028a000, 0xc000284100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x210 fp=0xc000127c68 sp=0xc000127be0 pc=0x862960
net/http.HandlerFunc.ServeHTTP(0xc000177080, 0xa35ac0, 0xc00028a000, 0xc000284100)
        /opt/go/src/net/http/server.go:1995 +0x44 fp=0xc000127c90 sp=0xc000127c68 pc=0x820f64
net/http.(*ServeMux).ServeHTTP(0xc0000b4e80, 0xa35ac0, 0xc00028a000, 0xc000284100)
        /opt/go/src/net/http/server.go:2375 +0x1d6 fp=0xc000127cf0 sp=0xc000127c90 pc=0x822e66
net/http.serverHandler.ServeHTTP(0xc0001a2a90, 0xa35ac0, 0xc00028a000, 0xc000284100)
        /opt/go/src/net/http/server.go:2774 +0xa8 fp=0xc000127d20 sp=0xc000127cf0 pc=0x824238
net/http.(*conn).serve(0xc000236000, 0xa36b40, 0xc0000b54c0)
        /opt/go/src/net/http/server.go:1878 +0x851 fp=0xc000127fc8 sp=0xc000127d20 pc=0x81ff21
runtime.goexit()
        /opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000127fd0 sp=0xc000127fc8 pc=0x462211
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2884 +0x2f4

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001d8100, 0x987ca4, 0xb, 0x9a9f00, 0x481c96)
        /opt/go/src/testing/testing.go:917 +0x381
testing.runTests.func1(0xc0001d8000)
        /opt/go/src/testing/testing.go:1157 +0x78
testing.tRunner(0xc0001d8000, 0xc00012bdf8)
        /opt/go/src/testing/testing.go:865 +0xc0
testing.runTests(0xc0000bec40, 0xdc2cc0, 0x1, 0x1, 0x0)
        /opt/go/src/testing/testing.go:1155 +0x2a9
testing.(*M).Run(0xc0000b6080, 0x0)
        /opt/go/src/testing/testing.go:1072 +0x162
main.main()
        _testmain.go:144 +0x1de

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
        /opt/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /opt/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /opt/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 21 [select]:
github.com/skycoin/hardware-wallet-daemon/src/daemon.(*Daemon).Run(0xc0001dc000, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/daemon/daemon.go:115 +0x894
github.com/skycoin/hardware-wallet-daemon/cmd/daemon.main()
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/cmd/daemon/daemon.go:39 +0x1fe
github.com/skycoin/hardware-wallet-daemon/cmd/daemon.TestRunMain(0xc0001d8100)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/cmd/daemon/daemon_test.go:14 +0x20
testing.tRunner(0xc0001d8100, 0x9a9f00)
        /opt/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
        /opt/go/src/testing/testing.go:916 +0x35a

goroutine 22 [chan receive]:
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/apputil.CatchInterrupt(0xc000148c60)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/apputil/apputil.go:20 +0xa0
created by github.com/skycoin/hardware-wallet-daemon/src/daemon.(*Daemon).Run
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/daemon/daemon.go:93 +0x443

goroutine 23 [chan receive]:
github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/apputil.CatchDebug()
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/vendor/github.com/skycoin/skycoin/src/util/apputil/apputil.go:44 +0xb8
created by github.com/skycoin/hardware-wallet-daemon/src/daemon.(*Daemon).Run
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/daemon/daemon.go:96 +0x45b

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f777411e090, 0x72, 0x0)
        /opt/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0000b6198, 0x72, 0x0, 0x0, 0x986690)
        /opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000b6180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0000b6180, 0x9ab118, 0xc000063df0, 0x938b40)
        /opt/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0000b0058, 0x5cf5794d, 0xc000063e18, 0x481c96)
        /opt/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000b0058, 0xc000063e68, 0x18, 0xc00008b080, 0x8246e4)
        /opt/go/src/net/tcpsock.go:260 +0x48
net/http.(*Server).Serve(0xc0001a2a90, 0xa35800, 0xc0000b0058, 0x0, 0x0)
        /opt/go/src/net/http/server.go:2859 +0x22d
github.com/skycoin/hardware-wallet-daemon/src/api.(*Server).Serve(0xc0000bf460, 0x0, 0x0)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/api/http.go:92 +0x84
github.com/skycoin/hardware-wallet-daemon/src/daemon.(*Daemon).Run.func2(0xc00014fd70, 0xc0000bf460, 0xc0001dc000, 0xc0000b2600)
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/daemon/daemon.go:109 +0x63
created by github.com/skycoin/hardware-wallet-daemon/src/daemon.(*Daemon).Run
        /usr/share/gocode/src/github.com/skycoin/hardware-wallet-daemon/src/daemon/daemon.go:106 +0x7ef

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7f777411dfc0, 0x72, 0xffffffffffffffff)
        /opt/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000230018, 0x72, 0x0, 0x1, 0xffffffffffffffff)
        /opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000230000, 0xc000177871, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000230000, 0xc000177871, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000232000, 0xc000177871, 0x1, 0x1, 0x0, 0x0, 0x0)
        /opt/go/src/net/net.go:177 +0x69
net/http.(*connReader).backgroundRead(0xc000177860)
        /opt/go/src/net/http/server.go:677 +0x58
created by net/http.(*connReader).startBackgroundRead
        /opt/go/src/net/http/server.go:673 +0xca
--- FAIL: TestWalletGeGenerateAddresses (2.69s)
    require.go:794: 
                Error Trace:    integration_test.go:666
                                                        integration_test.go:369
                Error:          Received unexpected error:
                                Post http://127.0.0.1:9510/api/v1/set_mnemonic: EOF
                Test:           TestWalletGeGenerateAddresses
--- FAIL: TestWalletApplySettings (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:400
                Error:          Received unexpected error:
                                Post http://127.0.0.1:9510/api/v1/apply_settings: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletApplySettings
--- FAIL: TestWalletBackup (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:655
                                                        integration_test.go:414
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletBackup
--- FAIL: TestWalletCheckMessageSignature (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:441
                Error:          Received unexpected error:
                                Post http://127.0.0.1:9510/api/v1/check_message_signature: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletCheckMessageSignature
--- FAIL: TestWalletFeatures (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:655
                                                        integration_test.go:450
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletFeatures
--- FAIL: TestWalletGenerateMnemonic (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:476
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletGenerateMnemonic
--- FAIL: TestWalletRecovery (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:500
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletRecovery
--- FAIL: TestWalletSetMnemonic (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:539
                Error:          Received unexpected error:
                                Post http://127.0.0.1:9510/api/v1/set_mnemonic: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletSetMnemonic
--- FAIL: TestWalletConfigurePinCode (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:553
                Error:          Received unexpected error:
                                Post http://127.0.0.1:9510/api/v1/configure_pin_code: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletConfigurePinCode
--- FAIL: TestWalletTransactionSign (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:655
                                                        integration_test.go:584
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletTransactionSign
--- FAIL: TestWalletWipe (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:633
                Error:          Received unexpected error:
                                Delete http://127.0.0.1:9510/api/v1/wipe: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletWipe
--- FAIL: TestWalletConnected (0.00s)
    require.go:794: 
                Error Trace:    integration_test.go:647
                Error:          Received unexpected error:
                                Get http://127.0.0.1:9510/api/v1/available: dial tcp 127.0.0.1:9510: connect: connection refused
                Test:           TestWalletConnected
FAIL
FAIL    github.com/skycoin/hardware-wallet-daemon/src/api/integration   2.714s
+ TEST_FAIL=1
+ echo 'shutting down daemon'
shutting down daemon
+ kill -s SIGINT 20193
./ci-scripts/integration-test.sh: line 99: kill: (20193) - No such process
+ wait 20193
+ rm daemon-integration-wallet-integration.test
+ exit 1
make: *** [Makefile:33: test-integration-wallet] Error 1
```

**Comment by therealssj** [comment]
@stdevAlDen its bcoz backup still doesnt work. looking into it

**Comment by stdevAlDen** [comment]
> @stdevAlDen its bcoz backup still doesnt work. looking into it

I was looking at the problem today and I reached a conclusion, so please let me know if you are agree:
- There is a bug in the way of we are handling the Connect/Close device connection? 
- This is the root cause of the bug?

If you can answer yes to these two question what I recommend here is using the [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) pattern, I'm very familiar with this but please let me know what do you thing.

**Comment by stdevAlDen** [comment]
> > @stdevAlDen its bcoz backup still doesnt work. looking into it
> 
> I was looking at the problem today and I reached a conclusion, so please let me know if you are agree:
> 
> * There is a bug in the way of we are handling the Connect/Close device connection?
> * This is the root cause of the bug?
> 
> If you can answer yes to these two question what I recommend here is using the [RAII](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization) pattern, I'm very familiar with this but please let me know what do you thing.

@therealssj The following sources are related to my previous comment:

https://github.com/skycoin/hardware-wallet-go/blob/cba497d953b76490fd52471f9f4f74d0072f7f4d/src/cli/recovery.go#L60

https://github.com/skycoin/hardware-wallet-go/blob/cba497d953b76490fd52471f9f4f74d0072f7f4d/src/skywallet/skywallet.go#L689-L692

https://github.com/skycoin/hardware-wallet-go/blob/cba497d953b76490fd52471f9f4f74d0072f7f4d/src/skywallet/skywallet.go#L711

https://github.com/skycoin/hardware-wallet-go/blob/cba497d953b76490fd52471f9f4f74d0072f7f4d/src/skywallet/skywallet.go#L807-L810

**Comment by therealssj** [comment]
Yes the issue with connection handling. 
Closing an already closed connection results in panic.
Will check raii thnx

**Comment by gz-c** [comment]
Duplicate Close() should never panic.  The problem is in the underlying connection library, if it is panicing.

**Comment by gz-c** [comment]
Searching for `fatal error: unexpected signal during runtime execution` shows that this is a go runtime message when using cgo and either there is something like a null pointer dereference in the C library, or you have found a go/cgo bug.  Which version of go are you using?

**Comment by stdevAlDen** [comment]
> Searching for `fatal error: unexpected signal during runtime execution` shows that this is a go runtime message when using cgo and either there is something like a null pointer dereference in the C library, or you have found a go/cgo bug. Which version of go are you using?

@therealssj go version go1.12.2 linux/amd64

**Pull request merged**
