### PR TITLE
Fix bug in TestDevice integration test ref #122

### LINKED ISSUE #122: Bug in integration TestDevice
**Describe the bug**
A confirmation message should be handle [from here](https://github.com/skycoin/hardware-wallet-go/blob/1ba329558c4eda58ea0b8585f5c096e32a294f9c/src/device-wallet/integration/device_interface_test.go#L116)(auto press feature for emulator)

**Environment information:**

Any

**Steps to Reproduce**

`make test`  it's failing

**Actual behavior**
Tests are not working

**Expected behavior**
Tests should work

**Additional context**
None

**Possible implementation**
Send a button ack [from here](https://github.com/skycoin/hardware-wallet-go/blob/1ba329558c4eda58ea0b8585f5c096e32a294f9c/src/device-wallet/integration/device_interface_test.go#L116).

### PR DESCRIPTION
**Pull request by stdevAlDen**
Fixes #122

Changes:
- Handle a button request by sending a button ack.

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuf specs?
no

Requires testing
no

https://github.com/skycoin/hardware-wallet-go/pull/123#issuecomment-490278412

### CODE REVIEW

**Comment by stdevAlDen** [comment]
@therealssj I found a bug in tests, I no know why this was hedden until now, it's related to button request/ack
Can you pleas check out it'is the righ way to solve this autopress button related issue?

PD: this should be tested against [this branch](https://github.com/simelo/skycoin-hardware-wallet/tree/stdevAlDen_t220_bug_in_SignMessage) or wait for merge

**Comment by stdevAlDen** [comment]
> Fixes #122
> 
> Changes:
> 
> * Handle a button request by sending a button ack.
> 
> Does this change need to mentioned in CHANGELOG.md?
> no
> 
> Requires changes in protobuf specs?
> no
> 
> Requires testing
> no

@olemis & @therealssj this depends on:
 - https://github.com/skycoin/hardware-wallet/pull/221
 - https://github.com/skycoin/hardware-wallet/pull/218

**Comment by therealssj** [comment]
@stdevAlDen like I said here https://github.com/skycoin/hardware-wallet-go/pull/121#issuecomment-489799469 
Check the fix i did in #116 
You need to fix the `SignMessage` function not this test.
Also remove the lock to make the tests pass

**Comment by stdevAlDen** [comment]
> @stdevAlDen like I said here [#121 (comment)](https://github.com/skycoin/hardware-wallet-go/pull/121#issuecomment-489799469)
> Check the fix i did in #116
> You need to fix the `SignMessage` function not this test.
> Also remove the lock to make the tests pass ( i will remove the lock anyways )

@olemis please do not merge/close this pr, after merging #116 I want to see if this still valid

@therealssj thank you for your feedback, I'm going to take a indeep look in #116 a lot of code...

**Comment by therealssj** [comment]
@stdevAlDen https://github.com/skycoin/hardware-wallet-go/pull/116/commits/bf649fff900ddfd525069c77a380818b0f871065#diff-e74c5dbf5b6565d473a1d8b1efd4df53

This is the fix instead of handling button ack in test

**Comment by stdevAlDen** [comment]
> test

@therealssj to be honest I do not feel confident about this, I have to re-think and convince myself that I understand everything, in any case thank you for the link :grinning:

**Comment by therealssj** [comment]
@stdevAlDen sure but 99% of code in that PR is not related to this. ( The PR is a refactor of the integration tests as previously they were not correct imo )
The related part is in the links

**Comment by stdevAlDen** [comment]
@therealssj yeah, thank you :)

**Comment by stdevAlDen** [comment]
> @stdevAlDen like I said here [#121 (comment)](https://github.com/skycoin/hardware-wallet-go/pull/121#issuecomment-489799469)
> Check the fix i did in #116
> You need to fix the `SignMessage` function not this test.
> Also remove the lock to make the tests pass ( i will remove the lock anyways )



> @stdevAlDen [bf649ff#diff-e74c5dbf5b6565d473a1d8b1efd4df53](https://github.com/skycoin/hardware-wallet-go/commit/bf649fff900ddfd525069c77a380818b0f871065#diff-e74c5dbf5b6565d473a1d8b1efd4df53)
> 
> This is the fix instead of handling button ack in test
> 
> -- Edit --
> [609545a](https://github.com/skycoin/hardware-wallet-go/commit/609545a0dcc36323aacaf0b8b02590404f642521) <-- and remove lock ( it is causing some sort of deadlock )

@therealssj 
I was checking some things that was worrying me about signing messages / transactions, but I already clarified my doubts :balloon: 
I only have one question to see if you can help me understand.

Maybe I'm wrong but I think that the message `ButtonRequest` should reach the user of the library, that's ussefull to implement user experience functionalities, for example if you are going to sign a transaction in the desktop wallet you should show to the end user something like for example:
"Confirm on the device that you want to make the transaction"

Check  out this comments: https://github.com/skycoin/hardware-wallet-protob/blob/b3a2d50a55c6fb047b895bec27204e0abae38900/protob/messages/messages.proto#L235-L250

I can not find a aquivalent code like this:
https://github.com/therealssj/hardware-wallet-go/blob/111-add-tests/src/skywallet/skywallet.go#L735-L740

From here:
https://github.com/therealssj/hardware-wallet-go/blob/111-add-tests/src/skywallet/skywallet.go#L746-L756

So I'm not sure if `Sign``Message`/`Transaction` should be equivalent about this.

**Comment by therealssj** [comment]
@stdevAlDen its trivial to implement in the daemon but then it adds another HTTP request which is not really needed.
In functons like backup it adds the load of 12-24 extra requests.

**Comment by stdevAlDen** [comment]
> @stdevAlDen its trivial to implement in the daemon but then it adds another HTTP request which is not really needed.
> In functons like backup it adds the load of 12-24 extra requests.
> 
> You can just wait for a response and meanwhile show a message as @Senyoret1 has done right now where he displays a popup asking the user to confirm the operation
> 
> If the operation fails then a response will be returned before a message is displayed to the user so the user never sees a message in this scenario

@therealssj Ok, thank you for your support

**Pull request closed without merging**
