### PR TITLE
add available function

### LINKED ISSUE #107: Connected always returns false if called separately
**Describe the bug**
https://github.com/skycoin/hardware-wallet-go/blob/2005503ec26b8ebce4d1edac4bb5c0683e4fcf80/src/device-wallet/device-wallet.go#L432-L435

if `Connected` is called from outside one of the function implementations it will always return false because there is no `d.Connect` call.

**Steps to Reproduce**

1. Connect wallet
2. use hw-daemon to call the `/connected` endpoint
3. returns false even though the device is connected

**Actual behavior**
returns false when device is connected

**Expected behavior**
Return true when device is connected

### PR DESCRIPTION
**Pull request by therealssj**
Fixes #107 

Changes:
- Modified `Connected` function 
- Add `Available` function to check if a skycoin wallet is connected to the system

>Note: Difference between `Connected` and `Available` is that connected checks if we can communicate with the device meanwhile available checks if a device is present.

Does this change need to mentioned in CHANGELOG.md?
yes 

Requires changes in protobuff specs?
no

Requires testing
no

The tests need improvement to test this

### CODE REVIEW

**Comment by therealssj** [comment]
@stdevAlDen @olemis do you have any idea why travis is failing?

**Comment by stdevAlDen** [comment]
@threalssj I'm on my way to the office, I 'm going to check when arrive

**Comment by stdevAlDen** [comment]
> @stdevAlDen @olemis do you have any idea why travis is failing?

@therealssj `serialization` / `deserialization` are "symetric" operations, you can use one to another even with different languages(as in our case) but the generated `proto` code its required to come from the same proto definitios, so if you are trying to use tracked proto definitions([`protob @ bab5101`](https://github.com/skycoin/hardware-wallet/tree/develop/tiny-firmware) vs [3ca36319c37b0d3092c93ced4fb5f3cab2a436b4](https://github.com/therealssj/hardware-wallet-go/blob/107-fix-connected-function-2/Gopkg.toml#L38)) from [develop](https://github.com/skycoin/hardware-wallet-go/blob/master/.travis.yml#L32), the generated `go` code should come from this `git` hash too, try if this solve the problem and let me know to make a review over other things in the pr :)

**Comment by therealssj** [comment]
@stdevAlDen oh right. that's prolly it. will wait for olemis to merge the PR

**Comment by stdevAlDen** [comment]
> @stdevAlDen oh right. that's prolly it. will wait for olemis to merge the PR

@therealssj  I catched our old "friend" here: https://github.com/skycoin/hardware-wallet-protob/pull/45

**Comment by olemis** [comment]
> @stdevAlDen oh right. that's prolly it. will wait for olemis to merge the PR

sorry , what PR ?

**Pull request merged**
